### ISSUE TITLE
NPE on sample app.[Untouched]

### ISSUE THREAD

**Issue by mahendranv** [ManuelPeinado/FadingActionBar#42]
- I have just imported the lib and stock sample app in Eclipse
- Resolved the dependencies
- Build successfully
- After install on my mobile observed NPE on activity launch

Find the log below:

FATAL EXCEPTION: main
Process: com.manuelpeinado.fadingactionbar.demo, PID: 4612
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.manuelpeinado.fadingactionbar.demo/com.manuelpeinado.fadingactionbar.demo.ScrollViewActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
    at android.app.ActivityThread.access$800(ActivityThread.java:145)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5081)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.manuelpeinado.fadingactionbar.FadingActionBarHelperBase.createScrollView(FadingActionBarHelperBase.java:242)
    at com.manuelpeinado.fadingactionbar.FadingActionBarHelperBase.createView(FadingActionBarHelperBase.java:139)
    at com.manuelpeinado.fadingactionbar.FadingActionBarHelperBase.createView(FadingActionBarHelperBase.java:114)
    at com.manuelpeinado.fadingactionbar.demo.ScrollViewActivity.onCreate(ScrollViewActivity.java:34)
    at android.app.Activity.performCreate(Activity.java:5241)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
    ... 11 more

**Comment by leonardossantos** [comment]
I am having the same issue. Did you find a solution for that?

**Comment by mahendranv** [comment]
I have cleaned my app and library 2 or 3 times and built again.

It worked.

**Comment by leonardossantos** [comment]
Thank you!

It was exactly that.

PS.: I think you should close this issue.

**Comment by mahendranv** [comment]
Closing after ~8 years. Remembering how painful it used to be an Android developer in 2014.
